server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      routes:
        - id: auth-service
          uri: http://auth-service:8082
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: bank-service
          uri: http://bankapi:8081
          predicates:
            - Path=/api/accounts/**,/api/transactions/**,/api/categories/**,/api/stats/**,/api/admin/**
          filters:
            - StripPrefix=1

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
              - http://127.0.0.1:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG